;-----------------------------------------------------------------------------
; cmpequ_int.inc
;-----------------------------------------------------------------------------

; Compare predicates for packed integers
CMP_EQ          equ 00h
CMP_LT          equ 01h
CMP_LE          equ 02h
CMP_FALSE       equ 03h
CMP_NEQ         equ 04h
CMP_NLT         equ 05h
CMP_GE          equ 05h
CMP_NLE         equ 06h
CMP_GT          equ 06h
CMP_TRUE        equ 07h
